
-- JK BARBEARIA - SUPABASE
-- Cole todo este arquivo no Supabase > SQL Editor > New query > Run.

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric(10,2) not null default 0 check (price >= 0),
  duration_minutes integer not null default 30 check (duration_minutes >= 10),
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  business_name text not null default 'JK Barbearia',
  phone text default '',
  instagram text default '',
  address text default '',
  open_time time not null default '08:00',
  close_time time not null default '19:00',
  slot_interval_minutes integer not null default 30 check (slot_interval_minutes between 15 and 180),
  work_days integer[] not null default array[1,2,3,4,5,6],
  blocked_dates date[] not null default '{}',
  updated_at timestamptz not null default now()
);

insert into public.settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  protocol uuid not null default gen_random_uuid(),
  client_name text not null check (char_length(client_name) between 2 and 80),
  phone text not null check (char_length(phone) between 8 and 25),
  service_id bigint references public.services(id) on delete restrict,
  service_name text not null,
  price numeric(10,2) not null default 0,
  booking_date date not null,
  booking_time time not null,
  notes text default '',
  status text not null default 'confirmado' check (status in ('confirmado','concluido','cancelado')),
  created_at timestamptz not null default now()
);

-- Impede dois agendamentos ativos no mesmo horário.
create unique index if not exists bookings_unique_active_slot
on public.bookings (booking_date, booking_time)
where status <> 'cancelado';

-- Dados iniciais.
insert into public.services (name,description,price,duration_minutes,image_url,active,sort_order)
select * from (values
('Corte Clássico','Tesoura e máquina com acabamento preciso.',35.00,40,'assets/corte-classico.svg',true,1),
('Degradê / Fade','Degradê moderno com linhas bem definidas.',40.00,45,'assets/degrade.svg',true,2),
('Barba Completa','Desenho da barba e acabamento.',30.00,30,'assets/barba.svg',true,3),
('Combo JK','Corte + barba para uma experiência completa.',65.00,70,'assets/combo.svg',true,4)
) as v(name,description,price,duration_minutes,image_url,active,sort_order)
where not exists (select 1 from public.services);

alter table public.services enable row level security;
alter table public.settings enable row level security;
alter table public.bookings enable row level security;

drop policy if exists "public read active services" on public.services;
create policy "public read active services" on public.services for select
to anon, authenticated using (active = true or auth.role() = 'authenticated');

drop policy if exists "admin manage services" on public.services;
create policy "admin manage services" on public.services for all
to authenticated using (true) with check (true);

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select
to anon, authenticated using (true);

drop policy if exists "admin update settings" on public.settings;
create policy "admin update settings" on public.settings for update
to authenticated using (true) with check (true);

drop policy if exists "admin read bookings" on public.bookings;
create policy "admin read bookings" on public.bookings for select
to authenticated using (true);

drop policy if exists "admin update bookings" on public.bookings;
create policy "admin update bookings" on public.bookings for update
to authenticated using (true) with check (true);

drop policy if exists "admin delete bookings" on public.bookings;
create policy "admin delete bookings" on public.bookings for delete
to authenticated using (true);

-- Retorna apenas os horários ocupados, sem revelar nome/telefone.
create or replace function public.get_booked_times(p_date date)
returns table(booked_time time)
language sql
security definer
set search_path = public
as $$
  select b.booking_time
  from public.bookings b
  where b.booking_date = p_date
    and b.status <> 'cancelado';
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;

-- Cria o agendamento de forma segura e retorna o protocolo.
create or replace function public.create_booking(
  p_client_name text,
  p_phone text,
  p_service_id bigint,
  p_booking_date date,
  p_booking_time time,
  p_notes text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.services%rowtype;
  cfg public.settings%rowtype;
  new_protocol uuid;
  weekday integer;
begin
  select * into s from public.services where id = p_service_id and active = true;
  if not found then raise exception 'Serviço inválido ou indisponível.'; end if;

  select * into cfg from public.settings where id = 1;

  if p_booking_date < current_date then raise exception 'Não é possível agendar uma data passada.'; end if;

  weekday := extract(dow from p_booking_date)::integer;
  if not (weekday = any(cfg.work_days)) then raise exception 'A barbearia não atende neste dia.'; end if;

  if p_booking_date = any(cfg.blocked_dates) then raise exception 'Esta data está bloqueada.'; end if;

  if p_booking_time < cfg.open_time or p_booking_time >= cfg.close_time then
    raise exception 'Horário fora do expediente.';
  end if;

  insert into public.bookings(client_name,phone,service_id,service_name,price,booking_date,booking_time,notes)
  values(trim(p_client_name),trim(p_phone),s.id,s.name,s.price,p_booking_date,p_booking_time,left(coalesce(p_notes,''),250))
  returning protocol into new_protocol;

  return new_protocol;
exception
  when unique_violation then
    raise exception 'Este horário já foi reservado. Escolha outro.';
end;
$$;

revoke all on function public.create_booking(text,text,bigint,date,time,text) from public;
grant execute on function public.create_booking(text,text,bigint,date,time,text) to anon, authenticated;

-- Bucket público para imagens de serviços.
insert into storage.buckets (id, name, public)
values ('service-images','service-images',true)
on conflict (id) do update set public = true;

drop policy if exists "public view service images" on storage.objects;
create policy "public view service images" on storage.objects for select
to anon, authenticated using (bucket_id = 'service-images');

drop policy if exists "admin upload service images" on storage.objects;
create policy "admin upload service images" on storage.objects for insert
to authenticated with check (bucket_id = 'service-images');

drop policy if exists "admin update service images" on storage.objects;
create policy "admin update service images" on storage.objects for update
to authenticated using (bucket_id = 'service-images') with check (bucket_id = 'service-images');

drop policy if exists "admin delete service images" on storage.objects;
create policy "admin delete service images" on storage.objects for delete
to authenticated using (bucket_id = 'service-images');
